kind: pipeline
name: go-echo-server

steps:
  - name: test
    image: golang
    commands:
      - echo "Test Go Web App"
  
  - name: build
    image: golang
    commands:
      - go build -o server
  
  - name: package
    image: plugins/docker
    settings:
      repo: quay.io/ottintl/kube-echo-server
      username:
        from_secret: username
      password: 
        from_secret: password
      registry: quay.io

