kind: pipeline
name: go-echo-server

steps:
  - name: test
    image: golang
    commands:
      - echo "Test Go Web App"
  
  - name: build
    image: golang
    commands:
      - go build -o server
  
  - name: package
    image: plugins/docker
    settings:
      repo: quay.io/ottintl/kube-echo-server
      username:
        from_secret: quay_username
      password: 
        from_secret: quay_password
      registry: quay.io
---
kind: secret
name: quay_username
get:
  path: dev/cicd/quay
  name: username
---
kind: secret
name: quay_password
get:
  path: dev/cicd/quay
  name: password







