workspace:
  base: /go
  path: src

pipeline:  
  test:
    image: "golang:latest"
    commands:
      - go version
      - go build -o server
  
  build:
    image: plugins/docker
    repo: quay.io/ottintl/kube-echo-server
    #username: $$DOCKER_USERNAME
    #password: $$DOCKER_PASSWORD
    tag: 1.2.0