workspace:
  base: /go
  path: src

pipeline:  
  build:
    image: "golang:latest"
    commands:
      - go version
      - go build -o server
  
  docker:
    image: plugins/docker
    repo: quay.io/ottintl/kube-echo-server
    secrets: [ docker_username, docker_password ]
    tag: latest