workspace:
  base: /go
  path: src

pipeline:  
  build:
    image: "golang:latest"
    commands:
      - go version
      - go build -o server
  
  docker:
    image: plugins/docker
    repo: quay.io/ottintl/kube-echo-server
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    tag: latest